name: Build Test and Deploy (master)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics
    - name: Build and test
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r requirements.txt
        mkdir test-reports
        nosetests -s --with-xunit --xunit-file=test-reports/test-report.xml
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install -r requirements.txt
        pip install semversioner==0.8.1

        previous_version=$(semversioner current-version)
        semversioner release
        new_version=$(semversioner current-version)
        semversioner changelog > CHANGELOG.md
        echo "Replace version '$previous_version' to '$new_version' in __version__.py ..."
        echo "__version__ = '$new_version'" > semversioner/__version__.py

        python setup.py sdist bdist_wheel
        twine upload dist/*
        
        git config --global user.name 'Semversioner Bot'
        git config --global user.email 'semversioner@users.noreply.github.com'
        git add .
        git commit -m "Update files for new version '${new_version}' [skip ci]"
        git push origin master
        
        git tag -a -m "Tagging for release ${new_version}" "${new_version}"
        git push origin ${new_version}
